/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caching.algorithms;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

public class SimpleLeastRecentUsedAlgorithmTest {

	private SimpleLeastRecentUsedAlgorithm<Integer> lruAlgorithm = new SimpleLeastRecentUsedAlgorithm<>(5);

	@Test
	public void show_test() {
		lruAlgorithm.add(5);
		lruAlgorithm.add(4);
		lruAlgorithm.add(3);
		lruAlgorithm.add(2);
		lruAlgorithm.add(1);
		lruAlgorithm.add(10);
		lruAlgorithm.add(10123);
		lruAlgorithm.add(577);
		lruAlgorithm.add(423);
		lruAlgorithm.add(664);
		lruAlgorithm.add(662);
		lruAlgorithm.add(-510);
		lruAlgorithm.add(1000);

		final String expectedResult = " 423 664 663 -510 1000 ";

		Assertions.assertThat(expectedResult).isEqualTo(lruAlgorithm.lru());
	}
}
